### ISSUE TITLE
ROS Launch Error (Noetic, ubunto 20.04)

### ISSUE THREAD

**Issue by MF-Ahmed** [JulioPlaced/ExplORB-SLAM#2]
Hello!
while executing the launch file:  roslaunch robot_description single_house.launch
I get the following error. 

Depth Threshold (Close/Far Points): 5.99522
Enable localization only: false
[orb_slam2_rgbd-5] process has died [pid 46341, exit code -11, cmd /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM-main/devel/lib/orb_slam2_ros/orb_slam2_ros_rgbd /camera/rgb/image_raw:=robot_1/camera/rgb/image_raw /camera/depth_registered/image_raw:=robot_1/camera/depth_registered/image_raw /camera/rgb/camera_info:=robot_1/camera/rgb/camera_info /odom:=robot_1/odom __name:=orb_slam2_rgbd __log:=/home/user/.ros/log/260be8b2-8140-11ed-a523-1d3fa6732c0e/orb_slam2_rgbd-5.log].
log file: /home/user/.ros/log/260be8b2-8140-11ed-a523-1d3fa6732c0e/orb_slam2_rgbd-5*.log
[ WARN] [1671634814.997560425, 5.054000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1671634820.012793168, 10.063000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.
[ WARN] [1671634825.038664790, 15.073000000]: Timed out waiting for transform from base_footprint to map to become available before running costmap, tf error: canTransform: target_frame map does not exist.. canTransform returned after 0.1 timeout was 0.1.

Thanks

**Comment by JulioPlaced** [comment]
I could not reproduce that error. After building in fresh laptop, "single_house.launch" worked properly. After the message  "localization only: false" I obtained the following:

Depth Threshold (Close/Far Points): 5.99522
Enable localization only: false
New map created with 788 points


Perhaps a ROS-related error? Any extra info in the .log?

**Comment by MF-Ahmed** [comment]
.log file says 
[roslaunch][ERROR] 2022-12-21 17:29:20,692: [orb_slam2_rgbd-5] process has died [pid 71653, exit code -11, cmd /home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM-main/devel/lib/orb_slam2_ros/orb_slam2_ros_rgbd /camera/rgb/image_raw:=robot_1/camera/rgb/image_raw /camera/depth_registered/image_raw:=robot_1/camera/depth_registered/image_raw /camera/rgb/camera_info:=robot_1/camera/rgb/camera_info /odom:=robot_1/odom __name:=orb_slam2_rgbd __log:=/home/user/.ros/log/9b26d538-814c-11ed-a523-1d3fa6732c0e/orb_slam2_rgbd-5.log].
log file: /home/user/.ros/log/9b26d538-814c-11ed-a523-1d3fa6732c0e/orb_slam2_rgbd-5*.log

Gazebo also does not start.

**Comment by JulioPlaced** [comment]
Gazebo GUI is disabled by default for performance. You can turn it on from the launch file, using "gazebo_gui" param. Perhaps that's a good point  to start debugging from -- check if RGBD is working properly in Gazebo-Rviz.

**Comment by MF-Ahmed** [comment]
Thanks for your comments. 
I have turned gazebo GUI, but it looks like there is some problem with the robot model ... and that's why orb_slam2_rgbd-6 is crashed? kindly  have a look at the screenshots

![Screenshot from 2022-12-22 10-06-38](https://user-images.githubusercontent.com/98259748/209101744-4b56e226-5b7a-4c30-b047-34214efca0ef.png)
![Screenshot from 2022-12-22 10-06-58](https://user-images.githubusercontent.com/98259748/209101761-ea0e01a6-636b-4564-adf0-7a032eebc649.png)
![Screenshot from 2022-12-22 10-07-36](https://user-images.githubusercontent.com/98259748/209101771-a564691b-0bad-4021-a351-0b361419d41f.png)
![Screenshot from 2022-12-22 10-07-42](https://user-images.githubusercontent.com/98259748/209101783-0d214e11-b0d0-4a47-ab98-446410edcc23.png)

**Comment by JulioPlaced** [comment]
Timeouts are certainly caused by SLAM algorithm not working (it publishes map-base TF), and the robot model should be OK (those warnings refer to xml version attribute in the .xacros). I think the problem is coming from ORB-SLAM. Did you install all dependencies? Could you try launch it separately? Try launch the script without ORB-SLAM and you will see if the error is coming from it (its my guess).

**Comment by MF-Ahmed** [comment]
I have installed all the dependencies and tried to run without ORBSLAM, the error is gone but I sill get the XML attribute warning.

**Comment by JulioPlaced** [comment]
That warning is not alarming (just Gazebo's SDF saying that XML version is not required).
Please, try launching single_house instead

**Comment by MF-Ahmed** [comment]
I have tried launching single_house.launch, with and without ORBSLAM but unfortunately the  same result.

**Comment by JulioPlaced** [comment]
As I mentioned previously, there is nothing wrong with the results you show. Only that "map" frame is not available -- obvious since there is no SLAM algorithm executed. If you change the fixed frame in RViz (e.g. to base), you'll be able to see the robot model instead of a white circle; if that worries you.

The problem in your case is that ORB-SLAM is not working properly. To debug it, you should execute ORB-SLAM alone to see the error that causes it to crash.

**Comment by MF-Ahmed** [comment]
Thanks for the help.  I'm trying to build  ORBSLAM2  from the src/3dParty/orb_slam_2_ros folder
and get the following error

/home/user/data/All_Study_Material/ASLAM_Papers_With_Code/ExplORB-SLAM-main/src/3dParty/orb_slam_2_ros/ros/include/Node.h:50:10: fatal error: orb_slam2_ros/SaveMap.h: No such file or directory
   50 | #include "orb_slam2_ros/SaveMap.h
maybe I need it to build with ROS but i don't know how to do it

**Comment by JulioPlaced** [comment]
Try the following:

- Go the Explorbslam dir:

> cd source/ExplORB-SLAM

- clean the workspace:

> catkin clean

- build ORB-SLAM only:

> catkin build orb_slam_2_ros --verbose 

For me, after a couple minutes it compiled successfully without errors (along with catkin_tools_prebuild).

**Comment by MF-Ahmed** [comment]
I'm able to build orb_slam2 ROS.  

Finished   << orb_slam2_ros:symlink                                                                                                                                                                             
Finished  <<< orb_slam2_ros                        [ 49.0 seconds ]                                                                                                                                             
[build] Summary: All 2 packages succeeded!                                                                                                                                                                      
[build]   Ignored:   4 packages were skipped or are skiplisted.                                                                                                                                                 
[build]   Warnings:  1 packages succeeded with warnings.                                                                                                                                                        
[build]   Abandoned: None.                                                                                                                                                                                      
[build]   Failed:    None.                                                                                                                                                                                      
[build] Runtime: 50.1 seconds total.                                                                                                                                                                            
[build] Note: Workspace packages have changed, please re-source setup files to use them.

**Comment by JulioPlaced** [comment]
Hello. I'm running out of ideas since I cannot reproduce it. Let's try a clean build and running ORB-SLAM in debug mode:

- Build first

> cd source/ExplORB-SLAM
> catkin clean
> catkin b
> source devel/setup.bash

- Add debug options:

In move_base_ORBSLAM.launch, change line 14 to the following:
  
`<node name="orb_slam2_rgbd" pkg="orb_slam2_ros" type="orb_slam2_ros_rgbd" output="screen" respawn="false" launch-prefix="xterm -e gdb --args">`

- Run:

> roslaunch robot_description single_house.launch

Type "run" in the xterm window and see what errors appear (none in my case)

**Comment by MF-Ahmed** [comment]
when typing "run" I got the following segmentation Fault 
![Screenshot from 2022-12-23 11-14-12](https://user-images.githubusercontent.com/98259748/209318211-e5a562d4-3b03-4c97-8b99-d1272346bbe1.png)

**Comment by JulioPlaced** [comment]
It appears to be related to OpenCV. Please write "bt" in gdb after the segmentation fault appears to trace it.

**Comment by MF-Ahmed** [comment]
ok after "bt" I get
![Screenshot from 2022-12-22 11-39-47](https://user-images.githubusercontent.com/98259748/209323953-47da500a-61cc-4a2d-8280-53bc63f11c04.png)

**Comment by MF-Ahmed** [comment]
I started all the procedure again .. but somehow this time I cannot build orb_slam_2_ros & get the following error
[build] Error: Given package 'orb_slam_2_ros' is not in the workspace and pattern does not match any package
do I need to source some folder?

**Comment by MF-Ahmed** [comment]
Thanks for the help. unfortunately I was unable to fix the OpenCV error.
So I installed ExploreORB-SLAM on a new machine. The OpenCV errors are now gone but Im getting the following error 
while executing roslaunch robot_description single_bookstore.launch   

[ INFO] [1672159916.836075189, 1.670000000]: No costmap conversion plugin specified. All occupied costmap cells are treaten as point obstacles.
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
[robot_1/move_base_node-6] process has died [pid 3987, exit code -6, cmd /home/usr/data/All_Study_Material/ASLAM_Papers_With_Code/active_graph_slam/devel/lib/move_base/move_base cmd_vel:=mobile_base/commands/velocity move_base_node/TebLocalPlannerROS/global_plan:=move_base_node/global_plan move_base_node/TebLocalPlannerROS/local_plan:=move_base_node/local_plan __name:=move_base_node __log:=/home/usr/.ros/log/c10f84b6-8606-11ed-89e5-43e98dbd8e72/robot_1-move_base_node-6.log].
log file: /home/usr/.ros/log/c10f84b6-8606-11ed-89e5-43e98dbd8e72/robot_1-move_base_node-6*.log

**Comment by MF-Ahmed** [comment]
unfortunately I was not able to resolve the OpenCV issue. So I reinstalled Ubunto and now everything works fine. Thanks for your help.
