### ISSUE TITLE
Problem with GPU

### ISSUE THREAD

**Issue by mmatteo-hub** [JulioPlaced/ExplORB-SLAM#3]
I am running the code on a Linux partition, Ubuntu 20.04.5 with ROS Noetic but I do not have an NVIDIA GPU.
My hardware is equipped with Intel Iris Plus Graphics 640.
How can I solve this problem by avoiding the use of GPU use and making it work also for non-NVIDIA-GPU-equipped PCs?
Thanks in advance.

**Comment by JulioPlaced** [comment]
Setting the parameter "gpu" in the launch file to false should do the trick. Feel free to reopen if that mode throws any errors.

**Comment by mmatteo-hub** [comment]
I tried this but actually it does not solve the problem.
I started reading all the code and I found there are some files which have the _cuda_ drivers directive.
In particular, in order to avoid them you have to delete the following lines:
- `decision_maker` folder:
line 19-20 and line 22 in `Functions.py`

- `frontier_detector` folder:
line 19-20 and line 22 in `Functions.py`

This makes a general PC without NVIDIA GPU drivers working correctly.

**Comment by JulioPlaced** [comment]
You are right, numba imports must be disabled too. I'll try to pull a modification for this soon.
