### ISSUE TITLE
Question About the Map file

### ISSUE THREAD

**Issue by MF-Ahmed** [JulioPlaced/ExplORB-SLAM#5]
Hi 
I was wondering where is the pose graph map file is saved?
Thnaks

**Comment by JulioPlaced** [comment]
Hello,
The pose-graph _per se_ (i.e., as a g2o/toro file) is not saved. We store a set of robot nodes, edges and map points and send them to the controller via ROS [(here are the subscribers)](https://github.com/JulioPlaced/ExplORB-SLAM/blob/main/src/decision_maker/src/python/Controller.py#L149).

In case you need the file, you can directly save it inside ORB-SLAM.
