### ISSUE TITLE
Obstacle detection problem 

### ISSUE THREAD

**Issue by MF-Ahmed** [JulioPlaced/ExplORB-SLAM#8]
Hi, 
I think the turtlebot has problems detecting obstacles during navigation and it simply crashes into walls, sofas, tables e.t.c. when  a goal position is given behind them using rviz  2D Nav Goal button.  Perhaps the teb local planner needs to be tuned ?
Thanks

**Comment by JulioPlaced** [comment]
Hello,
I have not tried directly commanding goals from Rviz, but if you changed the robot urdf or sensor configuration of the package, you should try tuning TEB params. I didnt not experience such problems before. Could you check the aspect of the costmaps in Rviz to have a little more context about what might be causing the error?

**Comment by MF-Ahmed** [comment]
Hi, 
Thanks for the information. Sorry for the late reply. Actually I'm using this same repo. without any changes. The problem is that there is no local and global costmap for obstacle detection, as a result the agent bumps into them.
After many effort in managed tuning with TEB planner params and also chaged the global planner from NavFn to GlobalPlanner which solved the obstacle detection problem (I also provided an global occupancy grid map as reference for global costmap) but now the information gain vector (Line 279 in controller.py) becomes zero for each frontier candidate after some time and t (line 277) goes to -inf. 
Perhaps it's not a good idea to adjust the global planner?
Thanks and Best regards
